// CyberLab Stage 3 - full course player
(function () {
const LESSONS={
'Cybersecurity Fundamentals':['Introduction to Cybersecurity','CIA Triad','Threats and Vulnerabilities','Authentication and Access Control','Malware and Phishing','Security Controls','Incident Response Basics','Security Best Practices'],
'Linux & Termux':['Linux Basics','Files and Directories','Essential Commands','Permissions','Processes','Package Management','Users and Groups','Shell Basics','Networking Commands','Safe Termux Practice'],
'Networking Fundamentals':['What is a Network?','IP Addresses','MAC Addresses','TCP and UDP','DNS','HTTP and HTTPS','Routing and Switching','Ports and Services','Network Security Basics'],
'Ethical Hacking':['Ethics and Authorization','Security Testing Lifecycle','Reconnaissance Concepts','Scanning Concepts','Vulnerability Assessment','Web Security Basics','Password Security','Social Engineering Awareness','Logging and Evidence','Reporting Findings','Remediation','Final Review'],
'Wireshark & Traffic Analysis':['Packet Analysis Basics','Capture Filters','Display Filters','Ethernet and ARP','IP Traffic','TCP Analysis','DNS and HTTP Traffic'],
'Secure Web Development':['Security by Design','Input Validation','Output Encoding','Authentication','Session Security','Access Control','Password Security','CSRF and XSS','Secure APIs','Final Security Review']};
const QUIZZES={
'Cybersecurity Fundamentals':[['What does CIA stand for?',['Confidentiality, Integrity and Availability','Central Intelligence Agency','Computer Internet Access','Cyber Information Architecture'],'A'],['What is a vulnerability?',['A security weakness that can be exploited','A verified identity','A backup','A network protocol'],'A'],['What does authentication verify?',['Identity','Permissions','A backup','A firewall rule'],'A']],
'Linux & Termux':[['Which command shows the current directory?',['pwd','cd','ls','mkdir'],'A'],['What does ls do?',['Lists directory contents','Changes permissions','Deletes a process','Changes the user'],'A'],['Why use least privilege?',['To reduce unnecessary access','To make everyone an admin','To disable login','To remove backups'],'A']],
'Networking Fundamentals':[['Which service resolves domain names?',['DNS','HTTP','SSH','ARP'],'A'],['Which protocol provides reliable ordered delivery?',['TCP','UDP','DNS','ICMP'],'A'],['What does a router primarily do?',['Forward traffic between networks','Store passwords','Render pages','Compile code'],'A']],
'Ethical Hacking':[['What is required before a security test?',['Permission and scope','A public target','A guessed password','An anonymous account'],'A'],['What is vulnerability assessment for?',['Finding and prioritizing weaknesses','Disabling services','Publishing data','Deleting logs'],'A'],['What belongs in a security report?',['Evidence, risk and remediation','Only screenshots','Private unrelated data','Unverified claims'],'A']],
'Wireshark & Traffic Analysis':[['What is a display filter for?',['Narrowing packets shown after capture','Deleting network packets','Changing a MAC address','Creating passwords'],'A'],['What does ARP help map on IPv4 LANs?',['IP address to link-layer address','DNS to HTTPS','Domain to port','TCP to UDP'],'A']],
'Secure Web Development':[['Where should protected-data authorization be enforced?',['On the server','Only in CSS','Only in the browser UI','Only in the page title'],'A'],['How should passwords be stored?',['With a modern password hash and unique salt','As plaintext','In JavaScript','Inside a URL'],'A'],['What is a key XSS defense?',['Context-appropriate output encoding','Disabling backups','Changing DNS','Increasing screen brightness'],'A']]};
const CONTENT={
'Introduction to Cybersecurity':`Cybersecurity is the practice of protecting computers, networks, applications, devices, accounts, and information from unauthorized access, misuse, disruption, modification, or destruction. It is broader than simply stopping hackers. A security program normally includes prevention, detection, response, recovery, risk management, user awareness, and continuous improvement. Security professionals think about what must be protected, who should be allowed to access it, what could go wrong, how an attack might be detected, and how normal operations can be restored. Important areas include network security, application security, identity and access management, cryptography, security monitoring, incident response, and digital forensics. Cybersecurity also has an ethical dimension: security testing must be performed only on systems and environments where the tester has permission. Learning the fundamentals gives you a foundation for understanding more specialized topics such as penetration testing, malware analysis, cloud security, and secure software development.`,
'CIA Triad':`The CIA Triad is one of the most important models in cybersecurity. CIA stands for Confidentiality, Integrity, and Availability. Confidentiality means information should be accessible only to authorized people, systems, or processes. Integrity means information should remain accurate, complete, and protected from unauthorized modification. Availability means systems and information should be accessible when legitimate users need them. These three goals help security teams evaluate risks and choose appropriate controls. For example, encryption can help protect confidentiality, access controls and integrity checks can help prevent or detect unauthorized changes, and backups, redundancy, monitoring, and recovery plans can improve availability. A single incident can affect more than one part of the triad. If an attacker steals a database, confidentiality is affected; if they alter records, integrity is affected; and if they destroy the database so users cannot access it, availability is affected. The CIA Triad is therefore a useful framework for thinking about security requirements rather than a single security tool.`,
'Threats and Vulnerabilities':`A threat is a potential cause of harm to a system, while a vulnerability is a weakness that could be exploited or could contribute to an unwanted security event. Risk connects these ideas by considering the possibility and impact of something going wrong. Threats can include malicious attackers, malware, accidental mistakes, equipment failure, natural events, or misuse of legitimate access. Vulnerabilities may include weak passwords, outdated software, excessive permissions, insecure configurations, exposed services, missing security controls, or unsafe application logic. A vulnerability does not automatically mean that an attack will succeed; security teams assess context, exposure, likelihood, and potential impact. Good vulnerability management includes identifying assets, discovering weaknesses, validating findings, prioritizing them by risk, applying fixes or mitigations, and checking that the problem has actually been resolved. Students should learn to distinguish between a vulnerability and a threat because the distinction improves security analysis and reporting.`,
'Authentication and Access Control':`Authentication and authorization are related but different security concepts. Authentication answers the question, “Who are you?” and may use something you know, such as a password; something you have, such as a security key; or something you are, such as a biometric characteristic. Authorization answers the question, “What are you allowed to do?” Access control applies those decisions to resources and actions. A secure system should verify identity and then enforce permissions according to the user's role and the sensitivity of the resource. Multi-factor authentication can reduce the impact of stolen passwords, while least privilege limits unnecessary access. Access decisions should be enforced on the server or trusted security boundary, not merely by hiding buttons in a web page. Regular review is also important because old accounts and unnecessary permissions increase risk.`,
'Malware and Phishing':`Malware is malicious software designed to perform unwanted or harmful actions. Common categories include viruses, worms, trojans, ransomware, spyware, and some forms of credential-stealing software. Phishing is a social-engineering technique that attempts to trick people into revealing information, opening a malicious attachment, visiting a fraudulent site, or taking another unsafe action. Modern phishing messages can imitate legitimate organizations and may use urgent language to encourage quick decisions. Defenses include security awareness, multi-factor authentication, email filtering, endpoint protection, software updates, backups, and careful verification of unexpected requests. Students should learn to inspect links and sender details, avoid opening suspicious attachments, and verify important requests through a separate trusted channel. In a security lab, phishing examples should be simulated with permission and without collecting real credentials.`,
'Security Controls':`Security controls are safeguards used to reduce security risk. They can be administrative, technical, or physical, and they can serve preventive, detective, corrective, or other security purposes. Examples include security policies, staff training, firewalls, access controls, encryption, backups, logging, monitoring, endpoint protection, locks, and recovery procedures. No single control provides complete protection, so organizations use layers of controls. This layered approach is often called defense in depth. For example, a system may use strong authentication to prevent unauthorized access, logging to record important events, monitoring to detect suspicious behavior, and backups to support recovery after data loss. Effective controls should be selected according to the assets, threats, vulnerabilities, business requirements, and acceptable level of risk. Controls should also be tested and reviewed because technology, users, and threats change over time.`,
'Incident Response Basics':`Incident response is the organized process used to prepare for, detect, analyze, contain, eradicate, and recover from security incidents. Preparation includes defining responsibilities, maintaining useful logs, creating communication plans, and practicing response procedures. Detection and analysis involve recognizing suspicious events, collecting relevant evidence, and determining what happened and which systems may be affected. Containment aims to limit further damage, while eradication removes the cause or malicious components. Recovery restores systems carefully and verifies that they are operating securely. Afterward, a lessons-learned review can identify improvements. Documentation is important throughout the process because accurate timelines and evidence help responders make decisions and communicate clearly. In a learning environment, students can practice incident response by analyzing a fictional alert, creating a timeline, identifying affected assets, and recommending containment and recovery actions.`,
'Security Best Practices':`Good cybersecurity is built from consistent habits and layered protections rather than one magic tool. Keep operating systems, browsers, applications, and security software updated. Use strong, unique passwords and a password manager, and enable multi-factor authentication wherever possible. Apply least privilege so accounts receive only the access they need. Back up important data and periodically verify that backups can actually be restored. Be cautious with unexpected links, attachments, downloads, and login requests. Secure networks with appropriate configuration and encryption, and monitor important systems for unusual activity. Organizations should maintain security policies, incident response plans, asset inventories, and regular risk assessments. Developers should use secure design, input validation, proper authentication, authorization, and safe handling of sensitive information. Finally, cybersecurity is a continuous process: new vulnerabilities, technologies, and threats appear over time, so security controls and user knowledge must be reviewed and improved regularly.`,
'Linux Basics':`Linux is a family of operating systems built around the Linux kernel. It is widely used in servers, cloud systems, networking devices, development environments, security labs, and Android-based systems. A Linux system commonly includes the kernel, command-line tools, libraries, services, and a desktop environment when one is installed. The terminal provides a powerful way to manage files, processes, users, packages, and network settings. Understanding Linux is especially useful in cybersecurity because many security tools and servers run on Linux. Students should learn to work carefully with permissions and administrator privileges, because commands can affect important system files. Practice should be performed on your own computer, a virtual machine, or another authorized lab environment.`,
'Files and Directories':`Linux organizes information in a hierarchical filesystem that starts at the root directory, represented by /. Directories contain files and other directories, and paths can be absolute or relative. Understanding paths is essential when working with the terminal. Commands such as pwd, ls, cd, mkdir, touch, cp, mv, and rm allow users to navigate and manage files. Be careful with deletion and administrator privileges because mistakes can remove important data. A useful beginner exercise is to create a personal practice directory, add a few text files, copy and rename them, and then inspect the directory contents.`,
'Essential Commands':`Linux commands are small utilities that perform focused tasks. pwd shows the current working directory; ls lists directory contents; cd changes directories; mkdir creates directories; touch creates empty files; cat displays text; cp copies files; mv moves or renames files; rm removes files; and clear clears the terminal display. For example, a safe practice sequence is: mkdir cyberlab, cd cyberlab, touch notes.txt, echo "Linux practice" > notes.txt, and cat notes.txt. Use rm carefully because deleted files may not be recoverable. Commands should be practiced in a dedicated lab directory rather than against system files.`,
'Permissions':`Linux permissions control whether users can read, write, or execute files and directories. Permissions are commonly shown for the owner, group, and others. The chmod command changes permissions, while chown changes ownership. The principle of least privilege means giving accounts and programs only the access they actually need. For example, chmod u+x script.sh gives the owner execute permission on a script. Avoid using broad permissions simply to make a problem disappear. Understanding permissions is important in cybersecurity because incorrect access can expose sensitive files or allow unintended modification.`,
'Processes':`A process is a running instance of a program. Linux provides commands for viewing and managing processes, including ps and top. Process information can help administrators troubleshoot performance and investigate unusual activity. Students should learn the difference between identifying a process and terminating it. In a lab, run a normal program, use ps to inspect processes, and compare the information with top. Do not terminate unknown or critical system processes on a real machine just for practice.`,
'Package Management':`Package managers install, update, and remove software while handling dependencies. The exact commands depend on the Linux distribution. Debian-based systems commonly use apt, while other distributions use tools such as dnf or pacman. Keeping packages updated is important because security fixes are often distributed through updates. Before installing software, verify the package source and understand what will be installed. In a lab, students can practice checking available updates and installing a small, trusted package.`,
'Users and Groups':`Linux uses users and groups to organize identity and access. Commands such as whoami and id show information about the current account, while administrators can use appropriate account-management tools to manage users and groups. Separating privileges between accounts reduces the chance that one compromised process receives unnecessary control. Students should understand the purpose of administrative accounts and avoid using elevated privileges for routine tasks.`,
'Shell Basics':`A shell interprets commands and provides features such as variables, command history, pipelines, redirection, and scripts. Bash is a common shell on Linux. Commands can be combined to process information efficiently, but students should understand each command before creating a longer command chain. In a safe lab, practice echo, variables, redirection, and simple scripts that only read or create files inside a practice directory.`,
'Networking Commands':`Linux includes useful networking commands for inspecting local configuration and connectivity. ip addr can show network interfaces and addresses, ping can test reachability where ICMP is permitted, and ss can display socket information. These tools are useful for troubleshooting and security investigation. Only inspect or test systems you own or are authorized to administer.`,
'Safe Termux Practice':`Termux provides a terminal environment on Android and can be used to learn Linux concepts without requiring a traditional desktop Linux installation. Start with harmless tasks such as checking the current directory, listing files, creating a practice folder, and using the package manager to keep the environment updated. Commands such as pwd, ls, cd, mkdir, pkg update, and pkg upgrade are useful for learning. Termux does not grant permission to access other people's devices or networks; security testing must remain within authorized environments.`,
'TCP and UDP':'TCP provides connection-oriented reliable ordered delivery. UDP is connectionless and has lower overhead but does not provide TCP-style reliability.',
'DNS':'DNS translates domain names into IP addresses and provides other records used by network applications.',
'HTTP and HTTPS':'HTTP supports web communication. HTTPS uses TLS to protect the connection against eavesdropping and tampering in transit.',
'Packet Analysis Basics':'Packet analysis examines network traffic to understand protocols, communication patterns and troubleshooting information. Capture only traffic you are authorized to inspect.',
'CSRF and XSS':'CSRF abuses an authenticated browser session, while XSS causes untrusted content to execute in a web context. CSRF protections and output encoding help reduce these risks.'};
function esc(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML;}
function safe(v){return String(v).replace(/\\/g,'\\\\').replace(/'/g,"\\'");}
function ready(){return typeof supabaseClient!=='undefined'&&supabaseClient&&typeof currentUser!=='undefined'&&currentUser;}
async function progress(id){if(!ready())return[];const r=await supabaseClient.from('lesson_progress').select('lesson_number').eq('user_id',currentUser.id).eq('course_id',id);return(r.data||[]).map(x=>+x.lesson_number);}
function dashboard(p,c,q,cert){const a=document.getElementById('progress'),b=document.getElementById('progressText'),d=document.getElementById('coursesCompleted'),e=document.getElementById('quizScore'),f=document.getElementById('certificates');if(a)a.style.width=p+'%';if(b)b.textContent=p+'%';if(d)d.textContent=c;if(e)e.textContent=q+'%';if(f)f.textContent=cert;}
async function refresh(){if(!ready())return;try{const en=await supabaseClient.from('enrollments').select('course_id').eq('user_id',currentUser.id);const ids=(en.data||[]).map(x=>x.course_id);if(!ids.length){dashboard(0,0,0,0);return;}const [cs,ps,qs,ct]=await Promise.all([supabaseClient.from('courses').select('id,lesson_count').in('id',ids),supabaseClient.from('lesson_progress').select('course_id,lesson_number').eq('user_id',currentUser.id),supabaseClient.from('quiz_attempts').select('score').eq('user_id',currentUser.id),supabaseClient.from('certificates').select('id').eq('user_id',currentUser.id)]);let total=0,done=0,cc=0;(cs.data||[]).forEach(c=>{total+=c.lesson_count;const n=(ps.data||[]).filter(x=>x.course_id===c.id).length;done+=Math.min(n,c.lesson_count);if(n>=c.lesson_count)cc++;});const avg=(qs.data||[]).length?Math.round((qs.data||[]).reduce((a,x)=>a+x.score,0)/(qs.data||[]).length):0;dashboard(total?Math.round(done/total*100):0,cc,avg,(ct.data||[]).length);}catch(e){console.warn(e);}}
window.startCourse=async function(name){if(!ready()){if(typeof openLogin==='function')openLogin();alert('Please log in before starting a course.');return;}try{const r=await supabaseClient.from('courses').select('id,name,lesson_count').eq('name',name).single();if(r.error||!r.data)throw r.error||new Error('Course not found. Run supabase-schema.sql.');const en=await supabaseClient.from('enrollments').upsert({user_id:currentUser.id,course_id:r.data.id},{onConflict:'user_id,course_id'});if(en.error)throw en.error;openPlayer(r.data,name,await progress(r.data.id));}catch(e){alert('Could not start course: '+(e.message||'Check Supabase policies.'));}};
function openPlayer(course,name,done){let m=document.getElementById('coursePlayerModal');if(!m){m=document.createElement('div');m.id='coursePlayerModal';m.className='course-player-modal';document.body.appendChild(m);}const list=LESSONS[name],pct=Math.round(done.length/list.length*100);m.innerHTML=`<div class="course-player"><div class="course-head"><div><div class="course-brand">&lt;CyberLab/&gt;</div><h2>${esc(name)}</h2><p>Complete lessons → pass quiz → earn certificate</p></div><button class="player-close" onclick="closeCoursePlayer()">×</button></div><div class="course-progress-wrap"><div><b>Course Progress</b><b id="coursePct">${pct}%</b></div><div class="course-progress"><i id="courseProgressFill" style="width:${pct}%"></i></div></div><div class="course-body"><main><section><h3>📚 Lessons</h3><p class="muted">Open a lesson, read it, then mark it complete.</p><div id="lessonList"></div></section><section class="quiz-panel"><h3>🧠 Course Quiz</h3><p class="muted">Answer every question. You need 70% or higher.</p><div id="courseQuiz"></div><button class="quiz-submit" onclick="submitCourseQuiz('${safe(name)}')">Submit Quiz</button><div id="quizFeedback"></div></section><section class="certificate-panel"><h3>🏆 Certificate</h3><p id="certificateMessage">Finish all lessons and pass the quiz with 70% or higher.</p><button id="certificateButton" disabled class="certificate-btn" onclick="generateCertificate('${safe(name)}')">Generate Certificate</button></section></main><aside><div class="summary"><h3>Summary</h3><div><strong id="doneCount">${done.length}</strong><span>Lessons done</span></div><div><strong>${list.length}</strong><span>Total lessons</span></div><div><strong>${(QUIZZES[name]||[]).length}</strong><span>Quiz questions</span></div></div></aside></div></div>`;m.classList.add('active');renderLessons(course,name,done);renderQuiz(QUIZZES[name]||[]);}
window.closeCoursePlayer=function(){const m=document.getElementById('coursePlayerModal');if(m)m.classList.remove('active');};
function renderLessons(course,name,done){const box=document.getElementById('lessonList');box.innerHTML=LESSONS[name].map((title,i)=>{const n=i+1,isDone=done.includes(n),body=CONTENT[title]||`In this lesson, you will learn the fundamentals of ${title}. Study the concept, understand its security purpose, and practice it only in your own device or authorized lab environment.`;return`<article class="lesson-card ${isDone?'is-done':''}"><button class="lesson-title" onclick="toggleLesson(${n})"><span class="lesson-num">${isDone?'✓':n}</span><span><strong>${esc(title)}</strong><small>${isDone?'Completed':'Open lesson'}</small></span><span id="arr${n}">+</span></button><div id="lesson${n}" class="lesson-content"><p>${esc(body)}</p><button class="mark-complete" ${isDone?'disabled':''} onclick="completeCourseLesson('${safe(name)}',${n})">${isDone?'✓ Completed':'Mark Complete'}</button></div></article>`;}).join('');}
window.toggleLesson=function(n){const x=document.getElementById('lesson'+n);if(x)x.classList.toggle('open');const a=document.getElementById('arr'+n);if(a)a.textContent=x&&x.classList.contains('open')?'−':'+';};
window.completeCourseLesson=async function(name,n){try{const c=await supabaseClient.from('courses').select('id,lesson_count').eq('name',name).single();if(c.error)throw c.error;const r=await supabaseClient.from('lesson_progress').upsert({user_id:currentUser.id,course_id:c.data.id,lesson_number:n},{onConflict:'user_id,course_id,lesson_number'});if(r.error)throw r.error;const done=await progress(c.data.id);renderLessons(c.data,name,done);const pct=Math.round(done.length/LESSONS[name].length*100);document.getElementById('courseProgressFill').style.width=pct+'%';document.getElementById('coursePct').textContent=pct+'%';document.getElementById('doneCount').textContent=done.length;await refresh();}catch(e){alert('Could not save lesson progress: '+e.message);}};
function renderQuiz(qs){document.getElementById('courseQuiz').innerHTML=qs.map((q,i)=>`<div class="quiz-question"><h4>${i+1}. ${esc(q[0])}</h4>${q[1].map((a,j)=>`<label><input type="radio" name="q${i}" value="${String.fromCharCode(65+j)}"><span>${esc(a)}</span></label>`).join('')}</div>`).join('');}
window.submitCourseQuiz=async function(name){const qs=QUIZZES[name]||[];let score=0;for(let i=0;i<qs.length;i++){const x=document.querySelector(`input[name="q${i}"]:checked`);if(!x){alert('Please answer all quiz questions.');return;}if(x.value===qs[i][2])score++;}const pct=Math.round(score/qs.length*100);document.getElementById('quizFeedback').innerHTML=`<div class="quiz-result ${pct>=70?'pass':'fail'}"><b>${pct>=70?'Quiz Passed!':'Quiz Not Passed'}</b><span>Score: ${pct}% (${score}/${qs.length})</span></div>`;try{const c=await supabaseClient.from('courses').select('id').eq('name',name).single();if(c.data)await supabaseClient.from('quiz_attempts').insert({user_id:currentUser.id,course_id:c.data.id,score:pct});const done=await progress(c.data.id);if(done.length>=LESSONS[name].length&&pct>=70){document.getElementById('certificateButton').disabled=false;document.getElementById('certificateMessage').textContent='Congratulations! You completed the course and passed the quiz.';}await refresh();}catch(e){console.warn(e);}};
window.generateCertificate=async function(name){try{const c=await supabaseClient.from('courses').select('id,lesson_count').eq('name',name).single();if(c.error)throw c.error;const done=await progress(c.data.id);const a=await supabaseClient.from('quiz_attempts').select('score').eq('user_id',currentUser.id).eq('course_id',c.data.id).order('attempted_at',{ascending:false}).limit(1);const score=a.data&&a.data[0]?a.data[0].score:0;if(done.length<c.data.lesson_count||score<70){alert('Complete all lessons and pass the quiz with 70% or higher.');return;}const id='CL-'+c.data.id+'-'+currentUser.id.slice(0,8).toUpperCase();await supabaseClient.from('certificates').upsert({user_id:currentUser.id,course_id:c.data.id,certificate_id:id},{onConflict:'user_id,course_id'});const student=(currentUser.user_metadata&&currentUser.user_metadata.full_name)||currentUser.email||'CyberLab Student';const w=window.open('','_blank');if(!w){alert('Allow pop-ups to generate your certificate.');return;}w.document.write(`<!doctype html><html><head><title>CyberLab Certificate</title><style>body{font-family:Arial;background:#07111f;margin:0;display:flex;align-items:center;justify-content:center;min-height:100vh}.cert{width:80%;padding:70px;text-align:center;background:#0a1625;color:white;border:6px solid #00ff9d;outline:2px solid #00ff9d;outline-offset:-20px}.brand,.course{color:#00ff9d}.tag{letter-spacing:5px}.name{font-size:44px}.course{font-size:30px}.id{margin-top:35px;color:#9aa8bb}@media print{body{background:white}.cert{background:white;color:black}.brand,.course{color:black}}</style></head><body><div class="cert"><div class="brand">&lt;CyberLab/&gt;</div><p class="tag">CERTIFICATE OF COMPLETION</p><h1 class="name">${esc(student)}</h1><p>has successfully completed</p><h2 class="course">${esc(name)}</h2><p>and passed the CyberLab knowledge assessment with <b>${score}%</b>.</p><p class="id">Certificate ID: ${id}<br>Issued: ${new Date().toLocaleDateString()}</p><p>Learn • Build • Secure</p></div><script>setTimeout(()=>window.print(),600)<\\/script></body></html>`);w.document.close();await refresh();}catch(e){alert('Certificate error: '+e.message);}};
window.addEventListener('load',()=>setTimeout(refresh,700));
})();
