// CyberLab Stage 3 - full course player
(function () {
const LESSONS={
'Cybersecurity Fundamentals':['Introduction to Cybersecurity','CIA Triad','Threats and Vulnerabilities','Authentication and Access Control','Malware and Phishing','Security Controls','Incident Response Basics','Security Best Practices'],
'Linux & Termux':['Linux Basics','Files and Directories','Essential Commands','Permissions','Processes','Package Management','Users and Groups','Shell Basics','Networking Commands','Safe Termux Practice'],
'Networking Fundamentals':['What is a Network?','IP Addresses','MAC Addresses','TCP and UDP','DNS','HTTP and HTTPS','Routing and Switching','Ports and Services','Network Security Basics'],
'Ethical Hacking':['Ethics and Authorization','Security Testing Lifecycle','Reconnaissance Concepts','Scanning Concepts','Vulnerability Assessment','Web Security Basics','Password Security','Social Engineering Awareness','Logging and Evidence','Reporting Findings','Remediation','Final Review'],
'Wireshark & Traffic Analysis':['Packet Analysis Basics','Capture Filters','Display Filters','Ethernet and ARP','IP Traffic','TCP Analysis','DNS and HTTP Traffic'],
'Secure Web Development':['Security by Design','Input Validation','Output Encoding','Authentication','Session Security','Access Control','Password Security','CSRF and XSS','Secure APIs','Final Security Review']};
const QUIZZES={
'Cybersecurity Fundamentals':[['What does CIA stand for?',['Confidentiality, Integrity and Availability','Central Intelligence Agency','Computer Internet Access','Cyber Information Architecture'],'A'],['What is a vulnerability?',['A security weakness that can be exploited','A verified identity','A backup','A network protocol'],'A'],['What does authentication verify?',['Identity','Permissions','A backup','A firewall rule'],'A']],
'Linux & Termux':[['Which command shows the current directory?',['pwd','cd','ls','mkdir'],'A'],['What does ls do?',['Lists directory contents','Changes permissions','Deletes a process','Changes the user'],'A'],['Why use least privilege?',['To reduce unnecessary access','To make everyone an admin','To disable login','To remove backups'],'A']],
'Networking Fundamentals':[['Which service resolves domain names?',['DNS','HTTP','SSH','ARP'],'A'],['Which protocol provides reliable ordered delivery?',['TCP','UDP','DNS','ICMP'],'A'],['What does a router primarily do?',['Forward traffic between networks','Store passwords','Render pages','Compile code'],'A']],
'Ethical Hacking':[['What is required before a security test?',['Permission and scope','A public target','A guessed password','An anonymous account'],'A'],['What is vulnerability assessment for?',['Finding and prioritizing weaknesses','Disabling services','Publishing data','Deleting logs'],'A'],['What belongs in a security report?',['Evidence, risk and remediation','Only screenshots','Private unrelated data','Unverified claims'],'A']],
'Wireshark & Traffic Analysis':[['What is a display filter for?',['Narrowing packets shown after capture','Deleting network packets','Changing a MAC address','Creating passwords'],'A'],['What does ARP help map on IPv4 LANs?',['IP address to link-layer address','DNS to HTTPS','Domain to port','TCP to UDP'],'A']],
'Secure Web Development':[['Where should protected-data authorization be enforced?',['On the server','Only in CSS','Only in the browser UI','Only in the page title'],'A'],['How should passwords be stored?',['With a modern password hash and unique salt','As plaintext','In JavaScript','Inside a URL'],'A'],['What is a key XSS defense?',['Context-appropriate output encoding','Disabling backups','Changing DNS','Increasing screen brightness'],'A']]};
const CONTENT={
'CIA Triad':'Confidentiality prevents unauthorized disclosure, Integrity protects data from unauthorized modification, and Availability keeps systems and services accessible when needed.',
'Permissions':'Linux permissions control read, write and execute access for the owner, group and others. Apply least privilege and avoid unnecessary administrator access.',
'Authentication and Access Control':'Authentication verifies identity. Authorization determines what an authenticated identity may access or do. Keep the two concepts separate.',
'Input Validation':'Validate input on the server using expected types, lengths, formats and allowed values. Client-side validation improves usability but cannot be trusted as the security boundary.',
'Access Control':'Protected operations should perform authorization checks on the server. Hiding a button in the browser is not an authorization mechanism.',
'Password Security':'Use strong unique passwords, MFA and a password manager. Applications should store passwords with modern password-hashing functions and unique salts.',
'Ethics and Authorization':'Security testing must have explicit permission, defined scope and rules of engagement. Only assess systems you are authorized to test.',
'TCP and UDP':'TCP provides connection-oriented reliable ordered delivery. UDP is connectionless and has lower overhead but does not provide TCP-style reliability.',
'DNS':'DNS translates domain names into IP addresses and provides other records used by network applications.',
'HTTP and HTTPS':'HTTP supports web communication. HTTPS uses TLS to protect the connection against eavesdropping and tampering in transit.',
'Packet Analysis Basics':'Packet analysis examines network traffic to understand protocols, communication patterns and troubleshooting information. Capture only traffic you are authorized to inspect.',
'CSRF and XSS':'CSRF abuses an authenticated browser session, while XSS causes untrusted content to execute in a web context. CSRF protections and output encoding help reduce these risks.'};
function esc(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML;}
function safe(v){return String(v).replace(/\\/g,'\\\\').replace(/'/g,"\\'");}
function ready(){return typeof supabaseClient!=='undefined'&&supabaseClient&&typeof currentUser!=='undefined'&&currentUser;}
async function progress(id){if(!ready())return[];const r=await supabaseClient.from('lesson_progress').select('lesson_number').eq('user_id',currentUser.id).eq('course_id',id);return(r.data||[]).map(x=>+x.lesson_number);}
function dashboard(p,c,q,cert){const a=document.getElementById('progress'),b=document.getElementById('progressText'),d=document.getElementById('coursesCompleted'),e=document.getElementById('quizScore'),f=document.getElementById('certificates');if(a)a.style.width=p+'%';if(b)b.textContent=p+'%';if(d)d.textContent=c;if(e)e.textContent=q+'%';if(f)f.textContent=cert;}
async function refresh(){if(!ready())return;try{const en=await supabaseClient.from('enrollments').select('course_id').eq('user_id',currentUser.id);const ids=(en.data||[]).map(x=>x.course_id);if(!ids.length){dashboard(0,0,0,0);return;}const [cs,ps,qs,ct]=await Promise.all([supabaseClient.from('courses').select('id,lesson_count').in('id',ids),supabaseClient.from('lesson_progress').select('course_id,lesson_number').eq('user_id',currentUser.id),supabaseClient.from('quiz_attempts').select('score').eq('user_id',currentUser.id),supabaseClient.from('certificates').select('id').eq('user_id',currentUser.id)]);let total=0,done=0,cc=0;(cs.data||[]).forEach(c=>{total+=c.lesson_count;const n=(ps.data||[]).filter(x=>x.course_id===c.id).length;done+=Math.min(n,c.lesson_count);if(n>=c.lesson_count)cc++;});const avg=(qs.data||[]).length?Math.round((qs.data||[]).reduce((a,x)=>a+x.score,0)/(qs.data||[]).length):0;dashboard(total?Math.round(done/total*100):0,cc,avg,(ct.data||[]).length);}catch(e){console.warn(e);}}
window.startCourse=async function(name){if(!ready()){if(typeof openLogin==='function')openLogin();alert('Please log in before starting a course.');return;}try{const r=await supabaseClient.from('courses').select('id,name,lesson_count').eq('name',name).single();if(r.error||!r.data)throw r.error||new Error('Course not found. Run supabase-schema.sql.');const en=await supabaseClient.from('enrollments').upsert({user_id:currentUser.id,course_id:r.data.id},{onConflict:'user_id,course_id'});if(en.error)throw en.error;openPlayer(r.data,name,await progress(r.data.id));}catch(e){alert('Could not start course: '+(e.message||'Check Supabase policies.'));}};
function openPlayer(course,name,done){let m=document.getElementById('coursePlayerModal');if(!m){m=document.createElement('div');m.id='coursePlayerModal';m.className='course-player-modal';document.body.appendChild(m);}const list=LESSONS[name],pct=Math.round(done.length/list.length*100);m.innerHTML=`<div class="course-player"><div class="course-head"><div><div class="course-brand">&lt;CyberLab/&gt;</div><h2>${esc(name)}</h2><p>Complete lessons → pass quiz → earn certificate</p></div><button class="player-close" onclick="closeCoursePlayer()">×</button></div><div class="course-progress-wrap"><div><b>Course Progress</b><b id="coursePct">${pct}%</b></div><div class="course-progress"><i id="courseProgressFill" style="width:${pct}%"></i></div></div><div class="course-body"><main><section><h3>📚 Lessons</h3><p class="muted">Open a lesson, read it, then mark it complete.</p><div id="lessonList"></div></section><section class="quiz-panel"><h3>🧠 Course Quiz</h3><p class="muted">Answer every question. You need 70% or higher.</p><div id="courseQuiz"></div><button class="quiz-submit" onclick="submitCourseQuiz('${safe(name)}')">Submit Quiz</button><div id="quizFeedback"></div></section><section class="certificate-panel"><h3>🏆 Certificate</h3><p id="certificateMessage">Finish all lessons and pass the quiz with 70% or higher.</p><button id="certificateButton" disabled class="certificate-btn" onclick="generateCertificate('${safe(name)}')">Generate Certificate</button></section></main><aside><div class="summary"><h3>Summary</h3><div><strong id="doneCount">${done.length}</strong><span>Lessons done</span></div><div><strong>${list.length}</strong><span>Total lessons</span></div><div><strong>${(QUIZZES[name]||[]).length}</strong><span>Quiz questions</span></div></div></aside></div></div>`;m.classList.add('active');renderLessons(course,name,done);renderQuiz(QUIZZES[name]||[]);}
window.closeCoursePlayer=function(){const m=document.getElementById('coursePlayerModal');if(m)m.classList.remove('active');};
function renderLessons(course,name,done){const box=document.getElementById('lessonList');box.innerHTML=LESSONS[name].map((title,i)=>{const n=i+1,isDone=done.includes(n),body=CONTENT[title]||`In this lesson, you will learn the fundamentals of ${title}. Study the concept, understand its security purpose, and practice it only in your own device or authorized lab environment.`;return`<article class="lesson-card ${isDone?'is-done':''}"><button class="lesson-title" onclick="toggleLesson(${n})"><span class="lesson-num">${isDone?'✓':n}</span><span><strong>${esc(title)}</strong><small>${isDone?'Completed':'Open lesson'}</small></span><span id="arr${n}">+</span></button><div id="lesson${n}" class="lesson-content"><p>${esc(body)}</p><button class="mark-complete" ${isDone?'disabled':''} onclick="completeCourseLesson('${safe(name)}',${n})">${isDone?'✓ Completed':'Mark Complete'}</button></div></article>`;}).join('');}
window.toggleLesson=function(n){const x=document.getElementById('lesson'+n);if(x)x.classList.toggle('open');const a=document.getElementById('arr'+n);if(a)a.textContent=x&&x.classList.contains('open')?'−':'+';};
window.completeCourseLesson=async function(name,n){try{const c=await supabaseClient.from('courses').select('id,lesson_count').eq('name',name).single();if(c.error)throw c.error;const r=await supabaseClient.from('lesson_progress').upsert({user_id:currentUser.id,course_id:c.data.id,lesson_number:n},{onConflict:'user_id,course_id,lesson_number'});if(r.error)throw r.error;const done=await progress(c.data.id);renderLessons(c.data,name,done);const pct=Math.round(done.length/LESSONS[name].length*100);document.getElementById('courseProgressFill').style.width=pct+'%';document.getElementById('coursePct').textContent=pct+'%';document.getElementById('doneCount').textContent=done.length;await refresh();}catch(e){alert('Could not save lesson progress: '+e.message);}};
function renderQuiz(qs){document.getElementById('courseQuiz').innerHTML=qs.map((q,i)=>`<div class="quiz-question"><h4>${i+1}. ${esc(q[0])}</h4>${q[1].map((a,j)=>`<label><input type="radio" name="q${i}" value="${String.fromCharCode(65+j)}"><span>${esc(a)}</span></label>`).join('')}</div>`).join('');}
window.submitCourseQuiz=async function(name){const qs=QUIZZES[name]||[];let score=0;for(let i=0;i<qs.length;i++){const x=document.querySelector(`input[name="q${i}"]:checked`);if(!x){alert('Please answer all quiz questions.');return;}if(x.value===qs[i][2])score++;}const pct=Math.round(score/qs.length*100);document.getElementById('quizFeedback').innerHTML=`<div class="quiz-result ${pct>=70?'pass':'fail'}"><b>${pct>=70?'Quiz Passed!':'Quiz Not Passed'}</b><span>Score: ${pct}% (${score}/${qs.length})</span></div>`;document.getElementById('quizScoreBadge')?.textContent;try{const c=await supabaseClient.from('courses').select('id').eq('name',name).single();if(c.data)await supabaseClient.from('quiz_attempts').insert({user_id:currentUser.id,course_id:c.data.id,score:pct});const done=await progress(c.data.id);if(done.length>=LESSONS[name].length&&pct>=70){document.getElementById('certificateButton').disabled=false;document.getElementById('certificateMessage').textContent='Congratulations! You completed the course and passed the quiz.';}await refresh();}catch(e){console.warn(e);}};
window.generateCertificate=async function(name){try{const c=await supabaseClient.from('courses').select('id,lesson_count').eq('name',name).single();if(c.error)throw c.error;const done=await progress(c.data.id);const a=await supabaseClient.from('quiz_attempts').select('score').eq('user_id',currentUser.id).eq('course_id',c.data.id).order('attempted_at',{ascending:false}).limit(1);const score=a.data&&a.data[0]?a.data[0].score:0;if(done.length<c.data.lesson_count||score<70){alert('Complete all lessons and pass the quiz with 70% or higher.');return;}const id='CL-'+c.data.id+'-'+currentUser.id.slice(0,8).toUpperCase();await supabaseClient.from('certificates').upsert({user_id:currentUser.id,course_id:c.data.id,certificate_id:id},{onConflict:'user_id,course_id'});const student=(currentUser.user_metadata&&currentUser.user_metadata.full_name)||currentUser.email||'CyberLab Student';const w=window.open('','_blank');if(!w){alert('Allow pop-ups to generate your certificate.');return;}w.document.write(`<!doctype html><html><head><title>CyberLab Certificate</title><style>body{font-family:Arial;background:#07111f;margin:0;display:flex;align-items:center;justify-content:center;min-height:100vh}.cert{width:80%;padding:70px;text-align:center;background:#0a1625;color:white;border:6px solid #00ff9d;outline:2px solid #00ff9d;outline-offset:-20px}.brand,.course{color:#00ff9d}.tag{letter-spacing:5px}.name{font-size:44px}.course{font-size:30px}.id{margin-top:35px;color:#9aa8bb}@media print{body{background:white}.cert{background:white;color:black}.brand,.course{color:black}}</style></head><body><div class="cert"><div class="brand">&lt;CyberLab/&gt;</div><p class="tag">CERTIFICATE OF COMPLETION</p><h1 class="name">${esc(student)}</h1><p>has successfully completed</p><h2 class="course">${esc(name)}</h2><p>and passed the CyberLab knowledge assessment with <b>${score}%</b>.</p><p class="id">Certificate ID: ${id}<br>Issued: ${new Date().toLocaleDateString()}</p><p>Learn • Build • Secure</p></div><script>setTimeout(()=>window.print(),600)<\/script></body></html>`);w.document.close();await refresh();}catch(e){alert('Certificate error: '+e.message);}};
window.addEventListener('load',()=>setTimeout(refresh,700));
})();
