-- CyberLab V2: Badges & Achievements
-- Run this entire file in Supabase SQL Editor.

create table if not exists public.badges (
  id bigint generated by default as identity primary key,
  code text unique not null,
  name text not null,
  description text not null,
  icon text not null default '🏆',
  created_at timestamptz not null default now()
);

create table if not exists public.user_badges (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  badge_id bigint not null references public.badges(id) on delete cascade,
  awarded_at timestamptz not null default now(),
  unique(user_id, badge_id)
);

alter table public.badges enable row level security;
alter table public.user_badges enable row level security;

drop policy if exists "Anyone can read badges" on public.badges;
create policy "Anyone can read badges"
on public.badges for select to anon, authenticated
using (true);

drop policy if exists "Users can read own badges" on public.user_badges;
create policy "Users can read own badges"
on public.user_badges for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Admins can read all user badges" on public.user_badges;
create policy "Admins can read all user badges"
on public.user_badges for select to authenticated
using (public.is_cyberlab_admin());

drop policy if exists "Users can earn own badges" on public.user_badges;
create policy "Users can earn own badges"
on public.user_badges for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Admins can manage badges" on public.badges;
create policy "Admins can manage badges"
on public.badges for all to authenticated
using (public.is_cyberlab_admin())
with check (public.is_cyberlab_admin());

drop policy if exists "Admins can manage user badges" on public.user_badges;
create policy "Admins can manage user badges"
on public.user_badges for all to authenticated
using (public.is_cyberlab_admin())
with check (public.is_cyberlab_admin());

insert into public.badges (code,name,description,icon) values
('FIRST_STEP','First Step','Enroll in your first CyberLab course.','🟢'),
('QUIZ_MASTER','Quiz Master','Score 90% or higher on a quiz.','🧠'),
('CYBER_DEFENDER','Cyber Defender','Complete Cybersecurity Fundamentals.','🛡️'),
('CYBERLAB_GRADUATE','CyberLab Graduate','Complete a course and pass its quiz.','🎓'),
('DEDICATED_LEARNER','Dedicated Learner','Complete three or more courses.','📚')
on conflict (code) do update set name=excluded.name,description=excluded.description,icon=excluded.icon;
