-- CyberLab Stage 2: database, enrollment, lesson progress, quizzes and certificates
-- Run this entire file once in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  name text not null unique,
  level text not null,
  lesson_count integer not null check (lesson_count > 0),
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.enrollments (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  enrolled_at timestamptz not null default now(),
  primary key (user_id, course_id)
);

create table if not exists public.lesson_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  lesson_number integer not null check (lesson_number > 0),
  completed_at timestamptz not null default now(),
  primary key (user_id, course_id, lesson_number)
);

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint references public.courses(id) on delete set null,
  score integer not null check (score between 0 and 100),
  attempted_at timestamptz not null default now()
);

create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  certificate_id text not null unique,
  issued_at timestamptz not null default now(),
  unique (user_id, course_id)
);

insert into public.courses (name, level, lesson_count, description) values
('Cybersecurity Fundamentals', 'Beginner', 8, 'Security principles, threats, vulnerabilities and defensive concepts.'),
('Linux & Termux', 'Beginner', 10, 'Linux commands, files, permissions, processes and terminal fundamentals.'),
('Networking Fundamentals', 'Beginner', 9, 'IP addresses, TCP/IP, DNS, HTTP and network architecture.'),
('Ethical Hacking', 'Intermediate', 12, 'Ethical security testing concepts through authorized lab environments.'),
('Wireshark & Traffic Analysis', 'Intermediate', 7, 'Inspect and understand network packets in controlled environments.'),
('Secure Web Development', 'Intermediate', 10, 'Secure coding concepts, authentication and input validation.')
on conflict (name) do update set level = excluded.level, lesson_count = excluded.lesson_count, description = excluded.description;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, new.raw_user_meta_data ->> 'full_name')
  on conflict (id) do update set full_name = excluded.full_name, updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.enrollments enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.certificates enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile" on public.profiles for select using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "Anyone can read courses" on public.courses;
create policy "Anyone can read courses" on public.courses for select using (true);

drop policy if exists "Users can read own enrollments" on public.enrollments;
create policy "Users can read own enrollments" on public.enrollments for select using (auth.uid() = user_id);

drop policy if exists "Users can create own enrollments" on public.enrollments;
create policy "Users can create own enrollments" on public.enrollments for insert with check (auth.uid() = user_id);

drop policy if exists "Users can read own lesson progress" on public.lesson_progress;
create policy "Users can read own lesson progress" on public.lesson_progress for select using (auth.uid() = user_id);

drop policy if exists "Users can create own lesson progress" on public.lesson_progress;
create policy "Users can create own lesson progress" on public.lesson_progress for insert with check (auth.uid() = user_id);

drop policy if exists "Users can delete own lesson progress" on public.lesson_progress;
create policy "Users can delete own lesson progress" on public.lesson_progress for delete using (auth.uid() = user_id);

drop policy if exists "Users can read own quiz attempts" on public.quiz_attempts;
create policy "Users can read own quiz attempts" on public.quiz_attempts for select using (auth.uid() = user_id);

drop policy if exists "Users can create own quiz attempts" on public.quiz_attempts;
create policy "Users can create own quiz attempts" on public.quiz_attempts for insert with check (auth.uid() = user_id);

drop policy if exists "Users can read own certificates" on public.certificates;
create policy "Users can read own certificates" on public.certificates for select using (auth.uid() = user_id);

-- Helpful indexes
create index if not exists enrollments_user_id_idx on public.enrollments(user_id);
create index if not exists lesson_progress_user_id_idx on public.lesson_progress(user_id);
create index if not exists quiz_attempts_user_id_idx on public.quiz_attempts(user_id);
create index if not exists certificates_user_id_idx on public.certificates(user_id);
